<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BigWalkMaker</AssemblyName>
    <RootNamespace>BigWalkMaker</RootNamespace>
    <DefineConstants>$(DefineConstants);IL2CPP</DefineConstants>
    <GameDir Condition="'$(GameDir)' == ''">$(GAME_DIR)</GameDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Il2CppInterop.Runtime" Version="1.5.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InteropAssemblies Include="$(GameDir)/BepInEx/interop/*.dll" />
    <CoreAssemblies Include="$(GameDir)/BepInEx/core/*.dll" />
    <Reference Include="%(InteropAssemblies.Filename)"><HintPath>%(InteropAssemblies.Identity)</HintPath><Private>False</Private></Reference>
    <Reference Include="%(CoreAssemblies.Filename)"><HintPath>%(CoreAssemblies.Identity)</HintPath><Private>False</Private></Reference>
  </ItemGroup>
</Project>
